Name: go-authorization

Log:
  Level: debug
  Format: console
  Directory: ./logs
  Development: true

HTTP:
  Host: 0.0.0.0
  Port: 2222

SuperAdmin:
  Username: root
  RealName: SuperAdmin
  Password: 123123

Auth:
  Enable: true
  TokenExpired: 7200
  IgnorePathPrefixes:
    - /pprof
    - /swagger
    - /api/v1/publics/user/login

Casbin:
  Enable: true
  Debug: false
  AutoLoad: false
  AutoLoadInternal: 10
  IgnorePathPrefixes:
    - /pprof
    - /swagger
    - /api/v1/publics/user

Redis:
  Host: 0.0.0.0
  Port: 6379
  Password:
  KeyPrefix: r

Database:
  Engine: postgres
  Name: go_authorization
  Host: 0.0.0.0
  Port: 5432
  Username: postgres
  Password: password
  TablePrefix: t
  Parameters: charset=utf8mb4&parseTime=True&loc=Local&allowNativePasswords=true&timeout=5s
  MaxLifetime: 7200
  MaxOpenConns: 150
  MaxIdleConns: 50
